name = "ip-worker-test-site"
main = "src/index.js"
compatibility_date = "2026-03-04"
workers_dev = true

[[d1_databases]]
binding = "DB"
database_name = "visitor_logs"
database_id = "903d519a-140d-4867-963f-b77e8a0dcbe3"
